In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

In [ ]:
from collections import Counter

In [ ]:
path_train = '/content/drive/MyDrive/Colab Notebooks/pql/kaggle_kidney_data/train.csv'
df=pd.read_csv(path_train)

# see data

In [ ]:
df.describe()

,id,MO HLADR+ MFI (cells/ul),Neu CD64+MFI (cells/ul),CD3+T (cells/ul),CD8+T (cells/ul),CD4+T (cells/ul),NK (cells/ul),CD19+ (cells/ul),CD45+ (cells/ul),Age,Sex 0M1F,Mono CD64+MFI (cells/ul),label
count,87.000000,86.000000,86.000000,87.000000,87.000000,87.000000,87.000000,87.000000,87.000000,87.000000,87.000000,86.000000,87.000000
mean,43.000000,1264.244186,290.383721,982.570115,479.340920,494.904023,212.732874,118.780920,1325.096437,40.218391,0.482759,2066.534884,0.333333
std,25.258662,765.452376,490.283499,617.332545,344.326452,311.836604,173.553264,96.218344,791.602538,10.461919,0.502599,1198.401364,0.474137
min,0.000000,112.000000,30.000000,74.400000,36.610000,39.590000,0.000000,4.200000,209.250000,19.000000,0.000000,72.000000,0.000000
25%,21.500000,685.500000,77.500000,549.390000,237.920000,272.745000,78.815000,52.425000,780.615000,33.000000,0.000000,1461.250000,0.000000
50%,43.000000,1108.500000,124.500000,871.710000,423.270000,459.720000,188.780000,89.790000,1179.270000,41.000000,0.000000,1757.500000,0.000000
75%,64.500000,1602.250000,244.500000,1268.085000,624.450000,624.360000,262.845000,155.450000,1617.725000,49.500000,1.000000,2238.250000,1.000000
max,86.000000,4145.000000,3124.000000,3791.230000,2548.100000,1517.810000,878.040000,485.860000,4757.280000,60.000000,1.000000,7515.000000,1.000000

In [ ]:
Counter(df['label'])

Counter({0: 58, 1: 29})

In [ ]:
# fill null data
df[df.isnull().values==True]

,id,MO HLADR+ MFI (cells/ul),Neu CD64+MFI (cells/ul),CD3+T (cells/ul),CD8+T (cells/ul),CD4+T (cells/ul),NK (cells/ul),CD19+ (cells/ul),CD45+ (cells/ul),Age,Sex 0M1F,Mono CD64+MFI (cells/ul),label
39,39,NaN,NaN,1336.54,739.71,550.3,68.46,192.07,1615.68,21,0,NaN,0
39,39,NaN,NaN,1336.54,739.71,550.3,68.46,192.07,1615.68,21,0,NaN,0
39,39,NaN,NaN,1336.54,739.71,550.3,68.46,192.07,1615.68,21,0,NaN,0

In [ ]:
df = df.fillna(df.mean())

In [ ]:
# drop unuseful column
df.drop(['id'], axis=1, inplace=True)

In [ ]:
# split label
y = df.loc[:,'label']
df = df.drop(['label'],axis=1)

In [ ]:
# scaling
from sklearn import preprocessing
# Get column names first
names = df.columns
# Create the Scaler object
scaler = preprocessing.StandardScaler()
# Fit your data on the scaler object
scaled_df = scaler.fit_transform(df)
scaled_df = pd.DataFrame(scaled_df, columns=names)

In [ ]:
scaled_df

,MO HLADR+ MFI (cells/ul),Neu CD64+MFI (cells/ul),CD3+T (cells/ul),CD8+T (cells/ul),CD4+T (cells/ul),NK (cells/ul),CD19+ (cells/ul),CD45+ (cells/ul),Age,Sex 0M1F,Mono CD64+MFI (cells/ul)
0,3.029007,4.536828,-1.168801,-1.173713,-1.026818,-1.232856,-1.197746,-1.292420,1.132671,-0.966092,4.599621
1,0.848207,-0.322697,0.749526,0.211949,1.229412,-0.583200,0.516069,0.521427,-1.943773,1.035098,-0.262155
2,0.425264,-0.452697,0.570519,0.598405,0.517212,0.186709,1.021694,0.628867,-1.174662,1.035098,-0.637826
3,-0.768229,-0.405236,-0.917829,-0.652976,-1.073200,-0.815303,-0.774598,-0.999792,1.421087,1.035098,-0.526391
4,-0.306957,-0.452697,0.195756,0.002714,0.420579,-0.138815,0.125325,0.130709,-1.174662,1.035098,-0.442815
...,...,...,...,...,...,...,...,...,...,...,...
82,-0.843566,-0.458887,1.285488,0.548134,2.008055,0.854678,0.000618,1.247362,0.171282,1.035098,-0.460543
83,-0.036009,-0.452697,0.596245,-0.149707,1.386231,-0.537301,-0.732889,0.253715,1.517226,-0.966092,-0.609123
84,-0.832992,1.468415,0.517177,0.229768,0.738926,-0.844569,-0.144056,0.202231,-0.597829,-0.966092,0.725565
85,-1.522918,1.224923,-0.064747,-0.294591,0.232732,-0.556136,-0.909131,-0.280172,-0.693968,1.035098,0.240991
86,-1.413217,-0.159681,-0.421279,-0.336917,-0.431894,-1.128540,0.378608,-0.543932,-2.039912,1.035098,0.319502

In [ ]:
scaled_df.describe()

,MO HLADR+ MFI (cells/ul),Neu CD64+MFI (cells/ul),CD3+T (cells/ul),CD8+T (cells/ul),CD4+T (cells/ul),NK (cells/ul),CD19+ (cells/ul),CD45+ (cells/ul),Age,Sex 0M1F,Mono CD64+MFI (cells/ul)
count,8.700000e+01,8.700000e+01,8.700000e+01,8.700000e+01,8.700000e+01,8.700000e+01,8.700000e+01,8.700000e+01,8.700000e+01,8.700000e+01,8.700000e+01
mean,2.143879e-16,-5.295891e-17,-7.975740e-17,3.298766e-16,-3.509326e-16,-2.781938e-16,1.097462e-16,1.199551e-16,-2.297013e-16,-4.083579e-17,3.164774e-16
std,1.005797e+00,1.005797e+00,1.005797e+00,1.005797e+00,1.005797e+00,1.005797e+00,1.005797e+00,1.005797e+00,1.005797e+00,1.005797e+00,1.005797e+00
min,-1.522918e+00,-5.372998e-01,-1.479648e+00,-1.293242e+00,-1.468569e+00,-1.232856e+00,-1.197746e+00,-1.417776e+00,-2.039912e+00,-9.660918e-01,-1.683796e+00
25%,-7.616204e-01,-4.382522e-01,-7.057644e-01,-7.052042e-01,-7.165513e-01,-7.760973e-01,-6.936369e-01,-6.918091e-01,-6.939680e-01,-9.660918e-01,-4.955777e-01
50%,-1.946122e-01,-3.412681e-01,-1.806203e-01,-1.637863e-01,-1.134825e-01,-1.388146e-01,-3.030502e-01,-1.852847e-01,7.514303e-02,-9.660918e-01,-2.596225e-01
75%,4.404633e-01,-9.055373e-02,4.651789e-01,4.238719e-01,4.175470e-01,2.904159e-01,3.833121e-01,3.718090e-01,8.923235e-01,1.035098e+00,1.367317e-01
max,3.807487e+00,5.847146e+00,4.576046e+00,6.042963e+00,3.299279e+00,3.855669e+00,3.837180e+00,4.360876e+00,1.901782e+00,1.035098e+00,4.599621e+00

In [78]:
# from imblearn.over_sampling import SMOTE
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [ ]:
"""
  over sampling
  but it is unuseful, so finally this data is not uesd
"""
# extract label
smt = SMOTE(sampling_strategy={1: 100,0:100})
# smo = SMOTE(sampling_strategy=0.4,random_state=42)
X_smo, y_smo = smt.fit_resample(scaled_df, y)

/usr/local/lib/python3.7/dist-packages/imblearn/utils/_validation.py:300: UserWarning: After over-sampling, the number of samples (100) in class 1 will be larger than the number of samples in the majority class (class #0 -> 58)
  f"After over-sampling, the number of samples ({n_samples})"
/usr/local/lib/python3.7/dist-packages/imblearn/utils/_validation.py:300: UserWarning: After over-sampling, the number of samples (100) in class 0 will be larger than the number of samples in the majority class (class #0 -> 58)
  f"After over-sampling, the number of samples ({n_samples})"

In [ ]:
from sklearn.model_selection import GridSearchCV 
from sklearn.model_selection import StratifiedKFold 
from sklearn.metrics import accuracy_score
import numpy as np

In [81]:
# see original score
model = RandomForestClassifier()
x_train, x_test, y_train, y_test = train_test_split(X_smo, y_smo, test_size = 0.1, random_state = 0)
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
print(accuracy_score(y_test , y_pred)*100)

95.0

In [83]:
"""
  adjust the parameter using gridsearchcv
  including
    1.max_depth
    2.n_estimators
    3.max_features
"""
param_test = {'max_features':range(2,12,2),'max_depth':range(2,12,2),'n_estimators':range(50,500,100)}
kflod = StratifiedKFold(n_splits=5, shuffle = True,random_state=7)
gsearch2 = GridSearchCV(estimator = RandomForestClassifier(oob_score=True),param_grid = param_test, scoring='accuracy',n_jobs = -1, cv=kflod)
gsearch2.fit(X_smo,y_smo)
print("Best: %f using %s" % (gsearch2.best_score_,gsearch2.best_params_))

Best: 0.955000 using {'max_depth': 8, 'max_features': 2, 'n_estimators': 250}

In [61]:
"""
  data preprocessing in test data
"""
def data_preprocessing(df):
  df.drop(['id'], axis=1, inplace=True)
  df = df.fillna(df.mean())
  # Get column names first
  names = df.columns
  # Create the Scaler object
  scaler = preprocessing.StandardScaler()
  # Fit the data on the scaler object
  scaled_df = scaler.fit_transform(df)
  scaled_df = pd.DataFrame(scaled_df, columns=names)
  return scaled_df

In [87]:
"""
  model in test, output submission.csv
"""
"""
  after gridsearchcv,the accuracy did not rise obviously, to prevent overfitting, the paras are not set too many
"""
test_path = '/content/drive/MyDrive/Colab Notebooks/pql/kaggle_kidney_data/test.csv'
test_x = pd.read_csv(test_path)
test_x = data_preprocessing(test_x)
rfc = RandomForestClassifier(n_estimators=200,oob_score=True)
rfc.fit(scaled_df, y)
test_y_pred = rfc.predict(test_x)
output=pd.DataFrame(test_y_pred.astype(np.int32),columns=['label'])
output['id']=range(output.shape[0])
output=output.loc[:,['id','label']]
output.to_csv('/content/drive/MyDrive/Colab Notebooks/pql/kaggle_kidney_data/submission.csv',index=False)

In [88]:
from joblib import dump, load
dump(rfc, 'drive/MyDrive/Colab Notebooks/pql/kaggle_kidney_data/rfc.joblib')

['drive/MyDrive/Colab Notebooks/pql/kaggle_kidney_data/rfc.joblib']